### ISSUE TITLE
Job Default Parameters

### ISSUE THREAD

**Issue by julianhall** [IAG-NZ/jenkins#100]
Hi - I have an issue when trying to invoke a Job using the Jobs default parameters:

I've tried:

` Invoke-JenkinsJob -Uri "http://xxx" -Credential $cred-Folder "yyy" -Name "zzz" 
`
But I get a 
"Nothing is submitted
Powered by Jetty:// 9.4.z-SNAPSHOT" 

So I tried it with empty parameters
 `Invoke-JenkinsJob -Uri "http://xxx" -Credential $cred -Folder "yyy" -Name "zzz" -Parameters @{}`

Which is successful at invoking the job, but it actaully wipes out all the default parameters.  When reviewing the job - you can see there are no parameters.  
(not sure if the bug lies here or with jenkins)

thanks.

**Comment by PlagueHO** [comment]
Hi @julianhall - what version of the module are you using?

I suspect I can see where the issue might be occurring. I'm just writing some unit tests to cover the function before making the required fix.

**Comment by julianhall** [comment]
I just installed last week, so if assume the latest release. I'll double
check and update if incorrect.

**Comment by PlagueHO** [comment]
This is still in progress as I needed to improve the unit testing before I made the change so that I know I'm not breaking anything. Sorry about the delay. Planning to complete this over the next week.
