### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by martin9700** [IAG-NZ/jenkins#102]
Hi, the build requirements for this project are kind of all over the place. Would it be possible to get a CONTRIBUTING.md file where you could outline exactly what you want changed?

**Comment by PlagueHO** [comment]
Hi @martin9700 - I'm half way through a bit of a clean up of this project (improving unit tests etc) so I'll include some work on the CONTRIBUTING.MD. I'll be most likely pulling it across from one of my other projects.
