### ISSUE TITLE
`Set-JenkinsTLSSupport` function fails because [Net.SecurityProtocolType] does not support op_addition

### ISSUE THREAD

**Issue by jeffprice6** [IAG-NZ/jenkins#76]
`Set-JenkinsTLSSupport` fails with the error: Method invocation failed because [System.Net.SecurityProtocolType] does not contain a method named 'op_Addition'.

`[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol + [Net.SecurityProtocolType]::Tls12`

could be updated to something like: 

`[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol.toString() + ', ' + [Net.SecurityProtocolType]::Tls12`

**Comment by PlagueHO** [comment]
Thanks for submitting this @jeffprice6 - I'll get onto this over the weekend.

**Comment by PlagueHO** [comment]
Thanks for raising this @jeffprice6 - it is much appreciated. I've submitted a PR to resolve this using your suggested code. It should be reviewed and released to the PS Gallery next week. Cheers!

**Comment by PlagueHO** [comment]
Hi @jeffprice6 - this has been released to the PowerShell Gallery.

**Comment by jeffprice6** [comment]
Thanks for the quick turnaround! The module has been a great help.. =>

---
Jeff Price
971.330.9734

**Comment by jeffprice6** [comment]
Thanks for the quick turnaround! The module has been a great help.. =>

**Comment by PlagueHO** [comment]
You're most welcome @jeffprice6 and glad this module has been helpful!
